-- 01_schema.sql
-- Estructura base de la BD para RidersApp
-- Modelo con claves sustitutas (id) y tablas catalogo para categorias y estados.

BEGIN;

CREATE TABLE IF NOT EXISTS estados (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(20) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categorias (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(30) NOT NULL UNIQUE,
    entregas_minimas     INTEGER NOT NULL CHECK (entregas_minimas >= 0),
    calificacion_minima  NUMERIC(3,2) NOT NULL CHECK (calificacion_minima >= 0 AND calificacion_minima <= 5),
    comision_porcentaje  NUMERIC(5,2) NOT NULL CHECK (comision_porcentaje >= 0 AND comision_porcentaje <= 100),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS riders (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(120) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    telefono      VARCHAR(20) NOT NULL UNIQUE,
    zona          VARCHAR(50) NOT NULL CHECK (BTRIM(zona) <> ''),
    categoria_id  INTEGER NOT NULL,
    fecha_ingreso DATE NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_riders_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categorias(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS entregas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id            INTEGER NOT NULL,
    descripcion         TEXT NOT NULL CHECK (BTRIM(descripcion) <> ''),
    valor               NUMERIC(10,2) NOT NULL CHECK (valor > 0),
    estado_id           SMALLINT NOT NULL,
    calificacion        NUMERIC(3,2) NULL CHECK (calificacion IS NULL OR (calificacion >= 0 AND calificacion <= 5)),
    fecha_creacion      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_entregas_rider
        FOREIGN KEY (rider_id)
        REFERENCES riders(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_entregas_estado
        FOREIGN KEY (estado_id)
        REFERENCES estados(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_estados_nombre
    ON estados (nombre);

CREATE INDEX IF NOT EXISTS idx_categorias_nombre
    ON categorias (nombre);

CREATE INDEX IF NOT EXISTS idx_riders_zona
    ON riders (zona);

CREATE INDEX IF NOT EXISTS idx_riders_categoria_id
    ON riders (categoria_id);

CREATE INDEX IF NOT EXISTS idx_entregas_rider_id
    ON entregas (rider_id);

CREATE INDEX IF NOT EXISTS idx_entregas_estado_id
    ON entregas (estado_id);

CREATE INDEX IF NOT EXISTS idx_entregas_fecha_creacion
    ON entregas (fecha_creacion);

CREATE INDEX IF NOT EXISTS idx_entregas_rider_fecha_estado
    ON entregas (rider_id, fecha_creacion, estado_id);

COMMIT;
